site_name: Cache OL dokumentasjon
nav:
    - Hjem: index.md
    - Brukere / Lag: users.md
    - Arrangement: event.md
    - Veipunkter: waypoints.md
    - Øvelser: exercises.md
    - Geochecker: checker.md
    - Tidtaker: timer.md
    - Resultater: results.md
    - Resultattavle: scoreboard.md

theme: 
  name: material
  language: 'no'
